GET http://localhost:8080/api/employees

###

POST http://localhost:8080/employees/
Content-Type: application/json

{
    "name": "Robert Downey",
    "level": "Senior",
    "position": "Sidekick"
}

###

DELETE http://localhost:8080/employees/6332ccb9510a829eeb8544dd


###

PATCH http://localhost:8080/api/employees/63405f7765f0dc8afca8e972
Content-Type: application/json

{
    "worklog": [
        {
        "workingHours": 1,
      "labelForWork": "shit"
        }
    ]
}

###

get http://localhost:8080/api/location